import Image from 'next/image'
import Head from 'next/head'
import styles from '../styles/page.module.scss'
import { Demos } from 'components/Demos/Demos'
import { AboutMe } from 'components/AboutMe'
import { ContactMe } from 'components/ContactMe/ContactMe'
import Nav from 'components/Nav'
import { Heading } from '@chakra-ui/react'


export default function Home() {
  return (
    <main className={styles.main}>
        <Head>
            <title>Harry Bell</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        {/* Make a nice heading */}
        <Heading p="20px 0">The voice over specialist</Heading>

      <div className={styles.center}>
        <Image
          className={styles.logo}
          src="/stock-mic2-removebg.png"
          alt="Next.js Logo"
          width={180}
          height={200}
          priority
        />
      </div>
      <Demos />
      <AboutMe />
      <ContactMe />
    </main>
  )
}
